name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Lint, coverage and build
      run: |
        npm i
#        npm run lint
        npm run coverage && npx codecov
        npm run build
      env:
        CI: true
        CODECOV_TOKEN: e017451c-146d-46cb-b1b3-d7932042bd9c
